### ISSUE TITLE
Will this mod keep existing now MC-174496 has been fixed?

### ISSUE THREAD

**Issue by Scubakay** [Fourmisain/KeepHeadNames#4]
Looks like the [head name bug](https://bugs.mojang.com/browse/MC-174496) was fixed, but I'm not sure if vanilla now also keeps the lore attached to placed heads. Will development for this mod be continued?

**Comment by Fourmisain** [comment]
Vanilla does not keep `lore` (nor `item_name` or `custom_data`) components, but as mentioned in the [changelog](https://curseforge.com/minecraft/mc-mods/keepheadnames/files/5293747), there's no need for a mod anymore as this functionality can now be easily built via a datapack.

All one needs to do is to copy the vanilla `player_head` block loot table and add `item_name`, `lore` and `custom_data` to the `copy_components` `include`.

Here's a working datapack doing just that: 
[KeepHeadData.zip](https://github.com/user-attachments/files/15858885/KeepHeadData.zip)

As long as Mojang doesn't add new components to copy, or changes the datapack format, this datapack should keep working in any future Minecraft version.

I'd upload it to the mod page, but since it's not actually a mod it technically requires it's own dedicated page.
I'll see what I can do.

**Comment by Fourmisain** [comment]
I created new project pages on ~~[Modrinth](https://modrinth.com/datapack/keep-head-data)~~ and [CurseForge](https://legacy.curseforge.com/minecraft/data-packs/keep-head-data), waiting for approval.

**Comment by Fourmisain** [comment]
Aaand I just noticed I can actually [upload datapacks](https://modrinth.com/datapack/keepheadnames/version/1.0.0) on mod pages on Modrinth, derp!

**Comment by Fourmisain** [comment]
CurseForge project has been approved.
Looks like there's no way for me to notify people about it (tried uploading empty additional files but those were all rejected), so I'll just pin this issue and add links everywhere.

**Comment by Scubakay** [comment]
Awesome! Thanks!
